name: Workflow template CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run ci-tests
        run: "echo 'I want make ci-tests'"
      
      - name: Print the content of this directory
        run: ls
